### ISSUE TITLE
Make event_metadata mandatory in EventBusProducer send() API

### ISSUE THREAD

**Issue by rgraber** [openedx/openedx-events#153]
The event_metadata parameter was left as optional in the send() method to avoid a complicated roll-out. Once edx-platform has been updated to use the new parameter we should go back and make it mandatory.

**Comment by robrap** [comment]
@rgraber: Does it make sense to just assign this to yourself and mark as groomed? It seems like it would be simplest just to consider this as a broken-out part of your work. Thoughts?

**Comment by rgraber** [comment]
Fine by me!
