### ISSUE TITLE
Organization scoped events

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/openedx-events#196]
## Description
This issue serves as a starting point for the discussion mentioned during the [Open edX Events guide pull request](https://github.com/openedx/openedx-events/pull/80), saying _organization proprietary events might live in this repo as well_.

Original comment: https://github.com/openedx/openedx-events/pull/80#discussion_r1146731541

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-events/issues/357
```

**Comment by robrap** [comment]
@ormsbee: Without you bringing up this topic (and I lost where you originally mentioned this), I probably would have just created something like a 2u-events repo. Either way, I'd probably use `2u` namespaced event types.

Are you still imagining that orgs should be able to add to this repo, and if so, can you add some of your thoughts here? Ultimately, this could turn in to an ADR for deciding for or against it. 

Additionally, were you thinking of this only for events that are produced within an open source repo, or even if it may be produced from a private repo? Either way, we'll need to choose whether it makes sense (or is a problem) to make the private events public.

Note: There is a separate licensing issue documented https://github.com/openedx/openedx-events/issues/184, but I'm hopeful that that can quickly be resolved.

**Comment by mariajgrimaldi** [comment]
@robrap: I'm not sure whether this discussion happened elsewhere, but I created an issue documenting how to create organization-specific events for now. The docs will explain that if events are org or client-specific, then create their definitions in your repository. I've seen people do that, but I don't know if we're doing it to keep it as the standard. At least it's working for the time being.

**Comment by robrap** [comment]
Thanks @mariajgrimaldi. This was really started on behalf of @ormsbee, so I'm hoping he can respond or close the ticket.

**Comment by ormsbee** [comment]
Thanks folks. I totally forgot about this ticket, and I honestly don't remember the discussion that we had around this.

I think my take was that org-specific events should not live in openedx-events, but that it should be possible for orgs to import everything that they would need to create their own events from openedx-events (i.e. declare instances of `OpenEdxPublicSignal` in their own repos).

But honestly, I've been out of the loop of openedx-events for a while now, so I have no idea where conversations around that have gone in the last year.

**Comment by robrap** [comment]
Ok. I think I must have misunderstood you long ago, so I am going to close this ticket. Thank you all!

**Comment by mariajgrimaldi** [comment]
Thank you both! Still, I'll include Dave's comments in the documentation since they're helpful.
