### ISSUE TITLE
Make ADR for versioning/dependency strategy around event bus implementations

### ISSUE THREAD

**Issue by timmc-edx** [openedx/openedx-events#209]
A/C

- [x] An ADR explaining why we're going to depend on all implementations of the event bus: https://github.com/openedx/openedx-events/pull/227
- [x] An issue for doing this better in the future (possibly an Axim issue)
  - Declined -- we're aware of the broader plugin dependencies issue and anything we do to solve that will help with the event bus implementations.

We reached a working consensus that we would depend on all implementations from any IDA that needed to use the Event Bus, but never made an ADR out of it: https://github.com/openedx/openedx-events/issues/88#issuecomment-1322556980

Let's finish that process.

**Comment by robrap** [comment]
@timmc-edx: Reminder to hopefully close this out. Thank you!
