### ISSUE TITLE
Idea: Tracking Log OpenEdxPublicSignal

### ISSUE THREAD

**Issue by bmtcril** [openedx/openedx-events#215]
This is a placeholder issue to start discussion on this topic. There is a desire to create a single “tracking log” OpenEdxPublicSignal that can be used for all tracking log events to facilitate event handling and transformation. Specifically https://github.com/openedx/wg-data/issues/28 calls for this, but several other xAPI use cases are in various levels of ideation.

The general idea is that once #210 is done we would like to add this new signal, and introduce a few other changes as outlined in the epic above to support configurable an event logs -> xAPI pipeline (as well as other consumers) that operators can tailor to their needs. Given the volume of tracking logs we're hoping that we can filter logs by event name on the producer side as part of this work.

**Comment by bmtcril** [comment]
@Ian2012 you've mentioned that you all might take on #210 to facilitate this work? @robrap @rgraber @timmc-edx does this seem like a feasible idea, or am I missing something important? I'm happy to have a quick meeting to discuss once folks have had a moment to think about it.

**Comment by robrap** [comment]
It seems like this would work. As part of https://github.com/openedx/openedx-events/issues/210, or as a follow-up, you might need to be able to add a function handler to the auto-producing side that enables the filtering before sending to the event bus, or some such idea.

**Comment by bmtcril** [comment]
Thanks @robrap , it looks like we'll be moving forward on this sooner rather than later. I'm sure we'll be pinging for reviews, but feel free to share any other thoughts that come up! I imagine an ADR will come out of #210 for review as well.
