### ISSUE TITLE
[Abstraction] Configurable loading of Event Bus producer implementation

### ISSUE THREAD

**Issue by timmc-edx** [openedx/openedx-events#87]
We need a way to load event-bus implementations based on configuration, so that IDAs don't have to depend directly on those libraries.

This issue is to define and implement an interface that allows an IDA to retrieve a **producer** instance by looking at Django settings. Consumer side has been split off to https://github.com/openedx/openedx-events/issues/147 since it is lower priority.

- [x] Define interface in openedx-events -- a documented set of functions/module variables and a loader that reads the settings. PR: https://github.com/openedx/openedx-events/pull/85
- [x] Implement producer API in event-bus-kafka. PR: https://github.com/openedx/event-bus-kafka/pull/14
- [x] Add link from openedx-events producer API docs to event-bus implementation (to better document the config with a real example): https://github.com/openedx/openedx-events/pull/150
- [x] Switch CMS and any other producers to use new interface and remove any current direct references to the `edx_event_bus_kafka` module that are present: https://github.com/openedx/edx-platform/pull/31356

**Comment by robrap** [comment]
@timmc-edx: I'm calling this groomed and assigned it to you, because I think our assumptions were based on you closing this out.
