### ISSUE TITLE
[OEP-55 PILOT] catalog-info correctness setup

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/openedx-events#94]
### Description
The repo catalog-info must show correct/valid information about the project's current status, and the maintainers can find information on:
       - Seeing what you own.
       - Seeing what other people own.
       - Seeing how repos relate to each other.

**Comment by mariajgrimaldi** [comment]
Hello there @sarina @feanil! I hope you're doing great. 

I have a question about the current backstage setup. After logging in and clicking on the component "docs", this message appears:

![image](https://user-images.githubusercontent.com/64440265/188159780-aa57a3dc-a168-4375-9300-c5fd2a8992b9.png)

should we add the missing annotation? or is it part of the current setup?

Thanks! :heart:

**Comment by sarina** [comment]
I'm not sure. Feanil is on holiday but will be able to answer when he's back sometime next week.

**Comment by feanil** [comment]
@mariajgrimaldi that docs tabs is for the built-in Markdown docs which we're not using, So I think the better option will be to add a link to the links section of the main page.  I'll add a ticket to remove that tab to reduce confusion.

**Comment by mariajgrimaldi** [comment]
Good! Thank you both :1st_place_medal:

**Comment by mariajgrimaldi** [comment]
I'm closing this since we can use backstage to check the library's info :1st_place_medal:
